### ISSUE TITLE
Move github workflow test tweaks to separate installation script

### ISSUE THREAD

**Issue by percyfal** [NBISweden/ancient-microbiome-smk#11]
There are currently three post-installation configuration steps that are required to make github actions work:

1. building of krakendb database
2. building of krona taxonomy
3. reducing malt runtime memory

These steps should be placed in a separate post-(test?)-installation script as these steps are also required for local tests but currently not implemented.

**Comment by LeandroRitter** [comment]
One has to also manually build bowtie2 index, right? Like this:

bowtie2-build --large-index ref.fa ref.fa --threads 4

**Comment by percyfal** [comment]
@LeandroRitter I actually added the bowtie build dependency to bowtie align, so that shouldn't be necessary.
