### ISSUE TITLE
Adapt number of threads in authentication script

### ISSUE THREAD

**Issue by clami66** [NBISweden/ancient-microbiome-smk#45]
In `scripts/authentic.sh` the number of threads is hardcoded as 4, guess this should be passed as parameter from the `-j` option of the Snakemake invocation?

**Comment by percyfal** [comment]
Yes, good that you bring this up. This is due to the fact that MaltExtract and postprocessing.AMPS.r were hardcoded to use 4 threads. The threads should be parametrized with an extra option to `authentic.sh`.
